/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BillController;
import model.Bill;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class BillsJFrame extends javax.swing.JFrame {

    private BillController billController;

    public BillsJFrame() {
        initComponents();
        
        

        try {
            Connection connection = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/dental_clinic",
                "root",
                System.getenv("DENTAL_DB_PASSWORD")
            );

            billController = new BillController(connection);
            loadAppointmentIds();
            loadBills();
            
            jTextField3.setEditable(false);
            
            cmbAppointment.addActionListener(e -> calculateAmount());

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Database Connection Error: " + e.getMessage()
            );
        }
    }
    private void calculateAmount() {

    try {

        if (cmbAppointment.getSelectedItem() == null) {
            return;
        }

        int appointmentId =
                Integer.parseInt(
                    cmbAppointment.getSelectedItem().toString()
                );

        double total =
                billController.calculateTotalBill(appointmentId);

        jTextField3.setText(String.format("%.2f", total));

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Error calculating bill: " + e.getMessage()
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
            this,
            "Invalid Appointment ID!"
        );
    }
}
    
   private void loadAppointmentIds() {

    cmbAppointment.removeAllItems();

    try {

        List<Integer> ids = billController.getAppointmentIds();

        for (Integer id : ids) {
            cmbAppointment.addItem(String.valueOf(id));
        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error loading Appointment IDs: " + e.getMessage()
        );
    }
}
    /**
     * Creates new form BillsJFrame
     */
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBills = new javax.swing.JTable();
        cmbAppointment = new javax.swing.JComboBox<>();
        btnPrint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dental Clinic - Billing");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Bill ID:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Appointment ID:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Amount:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Bill Date:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Payment Status:");

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 102));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Dental Clinic - Billing");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Paid" }));

        tblBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Appointment ID", "Amount", "Bill Date", "Payment Status"
            }
        ));
        tblBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBills);

        btnPrint.setBackground(new java.awt.Color(0, 0, 102));
        btnPrint.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("© 2026 Sunrise Dental Clinic ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sunrise_dental_clinic_logo_135x110.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(108, 108, 108)
                                .addComponent(jButton2)
                                .addGap(83, 83, 83)
                                .addComponent(jButton3))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addComponent(btnPrint)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btnPrint))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   

   
    try {

        // ==============================
        // 1. APPOINTMENT VALIDATION
        // ==============================

        if (cmbAppointment.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select an Appointment!"
            );

            return;
        }

        String appointmentText =
                cmbAppointment.getSelectedItem().toString().trim();

        if (appointmentText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select an Appointment!"
            );

            return;
        }

        int appointmentId =
                Integer.parseInt(appointmentText);

        if (appointmentId <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid Appointment ID!"
            );

            return;
        }


        // ==============================
        // 2. AMOUNT VALIDATION
        // ==============================

        String amountText =
                jTextField3.getText().trim();

        if (amountText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Bill Amount!"
            );

            jTextField3.requestFocus();
            return;
        }

        double amount =
                Double.parseDouble(amountText);

        if (amount <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill Amount must be greater than 0!"
            );

            jTextField3.requestFocus();
            return;
        }


        // ==============================
        // 3. BILL DATE VALIDATION
        // ==============================

        String billDate =
                jTextField4.getText().trim();

        if (billDate.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Bill Date!"
            );

            jTextField4.requestFocus();
            return;
        }


        // ==============================
        // 4. PAYMENT STATUS VALIDATION
        // ==============================

        if (jComboBox1.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select Payment Status!"
            );

            return;
        }

        String paymentStatus =
                jComboBox1.getSelectedItem()
                        .toString()
                        .trim();

        if (paymentStatus.isEmpty()
                || paymentStatus.equalsIgnoreCase("Select Status")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select Payment Status!"
            );

            return;
        }


        // ==============================
        // 5. CREATE BILL
        // ==============================

        Bill bill = new Bill(
                0,
                appointmentId,
                amount,
                billDate,
                paymentStatus
        );


        // ==============================
        // 6. SAVE BILL
        // ==============================

        if (billController.saveBill(bill)) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Bill Saved Successfully!\nBill ID: "
                    + bill.getBillId()
            );

            clearFields();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Bill Save Failed!"
            );
        }


    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter valid Appointment ID and Amount!"
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Database Error: " + e.getMessage()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
     try {

        // ==============================
        // 1. BILL ID VALIDATION
        // ==============================

        String billIdText =
                jTextField1.getText().trim();

        if (billIdText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a bill first!"
            );

            return;
        }

        int billId =
                Integer.parseInt(billIdText);

        if (billId <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid Bill ID!"
            );

            return;
        }


        // ==============================
        // 2. APPOINTMENT VALIDATION
        // ==============================

        if (cmbAppointment.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select an Appointment!"
            );

            return;
        }

        String appointmentText =
                cmbAppointment.getSelectedItem()
                        .toString()
                        .trim();

        if (appointmentText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select an Appointment!"
            );

            return;
        }

        int appointmentId =
                Integer.parseInt(appointmentText);

        if (appointmentId <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid Appointment ID!"
            );

            return;
        }


        // ==============================
        // 3. AMOUNT VALIDATION
        // ==============================

        String amountText =
                jTextField3.getText().trim();

        if (amountText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Bill Amount!"
            );

            jTextField3.requestFocus();
            return;
        }

        double amount =
                Double.parseDouble(amountText);

        if (amount <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill Amount must be greater than 0!"
            );

            jTextField3.requestFocus();
            return;
        }


        // ==============================
        // 4. BILL DATE VALIDATION
        // ==============================

        String billDate =
                jTextField4.getText().trim();

        if (billDate.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Bill Date!"
            );

            jTextField4.requestFocus();
            return;
        }


        // ==============================
        // 5. PAYMENT STATUS VALIDATION
        // ==============================

        if (jComboBox1.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select Payment Status!"
            );

            return;
        }

        String paymentStatus =
                jComboBox1.getSelectedItem()
                        .toString()
                        .trim();

        if (paymentStatus.isEmpty()
                || paymentStatus.equalsIgnoreCase("Select Status")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select Payment Status!"
            );

            return;
        }


        // ==============================
        // 6. CREATE BILL
        // ==============================

        Bill bill = new Bill(
                billId,
                appointmentId,
                amount,
                billDate,
                paymentStatus
        );


        // ==============================
        // 7. UPDATE BILL
        // ==============================

        if (billController.updateBill(bill)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill Updated Successfully!"
            );

            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Bill Update Failed!"
            );
        }


    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter valid Bill ID, Appointment ID and Amount!"
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Database Error: " + e.getMessage()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   try {

        int billId = Integer.parseInt(
                jTextField1.getText().trim()
        );

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this bill?",
                "Confirm Delete",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {

            if (billController.deleteBill(billId)) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Bill Deleted Successfully!"
                );

                clearFields();

            } else {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Bill Delete Failed!"
                );
            }
        }

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter a valid Bill ID!"
        );

    } catch (SQLException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Database Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         DashboardJFrame dashboard = new DashboardJFrame();
    dashboard.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillsMouseClicked
        int selectedRow = tblBills.getSelectedRow();

if (selectedRow >= 0) {

    // Bill ID
    jTextField1.setText(
        tblBills.getValueAt(selectedRow, 0).toString()
    );

    // Appointment ID
    cmbAppointment.setSelectedItem(
        tblBills.getValueAt(selectedRow, 1).toString()
    );

    // Amount
    jTextField3.setText(
        tblBills.getValueAt(selectedRow, 2).toString()
    );

    // Bill Date
    jTextField4.setText(
        tblBills.getValueAt(selectedRow, 3).toString()
    );

    // Payment Status
    jComboBox1.setSelectedItem(
        tblBills.getValueAt(selectedRow, 4).toString()
    );
}
    }//GEN-LAST:event_tblBillsMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {

        int selectedRow = tblBills.getSelectedRow();

        if (selectedRow == -1) {

            JOptionPane.showMessageDialog(
                this,
                "Please select a bill from the table first!"
            );

            return;
        }

        int billId = Integer.parseInt(
            tblBills.getValueAt(selectedRow, 0).toString()
        );

        int appointmentId = Integer.parseInt(
            tblBills.getValueAt(selectedRow, 1).toString()
        );

        double amount = Double.parseDouble(
            tblBills.getValueAt(selectedRow, 2).toString()
        );

        String billDate =
            tblBills.getValueAt(selectedRow, 3).toString();

        String paymentStatus =
            tblBills.getValueAt(selectedRow, 4).toString();

        double treatmentFee =
            billController.getTreatmentFee(appointmentId);

        double consultationFee = 1000.00;

        String receipt =
                "========================================\n"
              + "          SUNRISE DENTAL CLINIC\n"
              + "             BILL RECEIPT\n"
              + "========================================\n"
              + "Bill ID          : " + billId + "\n"
              + "Appointment ID   : " + appointmentId + "\n"
              + "Bill Date        : " + billDate + "\n"
              + "----------------------------------------\n"
              + "Treatment Cost   : Rs. "
              + String.format("%.2f", treatmentFee) + "\n"
              + "Consultation Fee : Rs. "
              + String.format("%.2f", consultationFee) + "\n"
              + "----------------------------------------\n"
              + "TOTAL            : Rs. "
              + String.format("%.2f", amount) + "\n"
              + "Payment Status   : " + paymentStatus + "\n"
              + "========================================\n"
              + "             Thank You!\n"
              + "========================================";

        javax.swing.JTextArea textArea =
            new javax.swing.JTextArea(receipt);

        textArea.setFont(
            new java.awt.Font(
                "Monospaced",
                java.awt.Font.PLAIN,
                12
            )
        );

        boolean complete =
            textArea.print();

        if (complete) {

            JOptionPane.showMessageDialog(
                this,
                "Bill printed successfully!"
            );

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Printing was cancelled."
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
            this,
            "Print Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnPrintActionPerformed
private void loadBills() {

    try {

        List<Bill> bills = billController.getAllBills();

        DefaultTableModel model =
                (DefaultTableModel) tblBills.getModel();

        model.setRowCount(0);

        for (Bill bill : bills) {

            model.addRow(new Object[]{
                bill.getBillId(),
                bill.getAppointmentId(),
                bill.getAmount(),
                bill.getBillDate(),
                bill.getPaymentStatus()
            });
        }

    } catch (SQLException e) {

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Database Error: " + e.getMessage()
        );
    }
}
    private void clearFields() {

    jTextField1.setText("");
    cmbAppointment.setSelectedIndex(0);
    jTextField3.setText("");
    jTextField4.setText("");

    jComboBox1.setSelectedIndex(0);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> cmbAppointment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tblBills;
    // End of variables declaration//GEN-END:variables
}
