/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ReportController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ReportsJFrame extends javax.swing.JFrame {
private ReportController reportController;

    /**
     * Creates new form ReportsJFrame
     */
   public ReportsJFrame() {
    initComponents();

    reportController = new ReportController();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnDailyReport = new javax.swing.JButton();
        btnMonthlyReport = new javax.swing.JButton();
        btnPatientTreatmentReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblDailyReportTitle = new javax.swing.JLabel();
        btnGenerateDaily = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDailyAppointments = new javax.swing.JTable();
        lblTotalAppointments = new javax.swing.JLabel();
        lblReportDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REPORTS");

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblTitle.setText("REPORTS");

        btnDailyReport.setBackground(new java.awt.Color(0, 0, 102));
        btnDailyReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDailyReport.setForeground(new java.awt.Color(255, 255, 255));
        btnDailyReport.setText("Daily  Appointments  Report");
        btnDailyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDailyReportActionPerformed(evt);
            }
        });

        btnMonthlyReport.setBackground(new java.awt.Color(0, 0, 102));
        btnMonthlyReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMonthlyReport.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlyReport.setText("MONTHLY REVENUE / BILLS  \nREPORT");
        btnMonthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyReportActionPerformed(evt);
            }
        });

        btnPatientTreatmentReport.setBackground(new java.awt.Color(0, 0, 102));
        btnPatientTreatmentReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPatientTreatmentReport.setForeground(new java.awt.Color(255, 255, 255));
        btnPatientTreatmentReport.setText(" PATIENT TREATMENT REPORT");
        btnPatientTreatmentReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientTreatmentReportActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDailyReportTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblDailyReportTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblDailyReportTitle.setText("DAILY APPOINTMENTS REPORT");

        btnGenerateDaily.setBackground(new java.awt.Color(0, 0, 102));
        btnGenerateDaily.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGenerateDaily.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateDaily.setText("GENERATE DAILY REPORT");
        btnGenerateDaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateDailyActionPerformed(evt);
            }
        });

        tblDailyAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Patient Name ", "Dentist Name", "Date", "Time", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblDailyAppointments);

        lblTotalAppointments.setText("Total Appointments:");

        lblReportDate.setText("Report Date:");

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("© 2026 Sunrise Dental Clinic ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(360, 360, 360))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sunrise_dental_clinic_logo_135x110.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPatientTreatmentReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnMonthlyReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnDailyReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(lblTotalAppointments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReportDate)
                .addGap(174, 174, 174))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(lblTitle)
                        .addContainerGap(328, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDailyReportTitle)
                                .addGap(227, 227, 227))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGenerateDaily)
                                .addGap(270, 270, 270))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDailyReportTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerateDaily))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDailyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btnMonthlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPatientTreatmentReport, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalAppointments)
                            .addComponent(lblReportDate))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateDailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateDailyActionPerformed
       try {

    String today = java.time.LocalDate.now().toString();

    List<String[]> appointments =
            reportController.getDailyAppointments(today);

    DefaultTableModel model =
            (DefaultTableModel) tblDailyAppointments.getModel();

    model.setRowCount(0);

    for (String[] row : appointments) {
        model.addRow(row);
    }

    lblTotalAppointments.setText(
            "Total Appointments: " + appointments.size()
    );

    lblReportDate.setText(
            "Report Date: " + today
    );

    if (appointments.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "No appointments found for today."
        );
    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error generating report: " + e.getMessage()
    );
}
    }//GEN-LAST:event_btnGenerateDailyActionPerformed

    private void btnMonthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyReportActionPerformed
        try {

        // Change table columns
        DefaultTableModel model =
                (DefaultTableModel) tblDailyAppointments.getModel();

       model.setColumnIdentifiers(new String[]{
    "Bill ID",
    "Appointment ID",
    "Bill Date",
    "Amount",
    "Payment Status"
});

        model.setRowCount(0);

        // Get current month
        String month =
                java.time.LocalDate.now()
                        .format(
                            java.time.format.DateTimeFormatter.ofPattern("yyyy-MM")
                        );

        List<String[]> bills =
                reportController.getMonthlyRevenue(month);

        double totalRevenue = 0;

        for (String[] row : bills) {

            model.addRow(row);

            totalRevenue += Double.parseDouble(row[3]);
        }

        lblTotalAppointments.setText(
                "Total Bills: " + bills.size()
        );

        lblReportDate.setText(
                "Month: " + month
        );

        lblDailyReportTitle.setText(
                "MONTHLY REVENUE / BILLS REPORT"
        );

        if (bills.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "No bills found for this month."
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error generating monthly report: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnMonthlyReportActionPerformed

    private void btnDailyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDailyReportActionPerformed
       // Change table columns for Daily Report
    DefaultTableModel model =
            (DefaultTableModel) tblDailyAppointments.getModel();

    model.setColumnIdentifiers(new String[]{
        "Appointment ID",
        "Patient Name",
        "Dentist Name",
        "Date",
        "Time",
        "Status"
    });

    // Clear old data
    model.setRowCount(0);

    // Change title
    lblDailyReportTitle.setText(
            "DAILY APPOINTMENTS REPORT"
    );

    // Clear summary labels
    lblTotalAppointments.setText(
            "Total Appointments:"
    );

    lblReportDate.setText(
            "Report Date:"
    );
    }//GEN-LAST:event_btnDailyReportActionPerformed

    private void btnPatientTreatmentReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientTreatmentReportActionPerformed


    try {

        DefaultTableModel model =
                (DefaultTableModel) tblDailyAppointments.getModel();

        model.setColumnIdentifiers(new String[]{
            "Patient ID",
            "Patient Name",
            "Treatment Name",
            "Description",
            "Fee"
        });

        model.setRowCount(0);

        List<String[]> treatments =
                reportController.getPatientTreatments();

        for (String[] row : treatments) {
            model.addRow(row);
        }

        lblDailyReportTitle.setText(
                "PATIENT TREATMENT REPORT"
        );

        lblTotalAppointments.setText(
                "Total Treatments: " + treatments.size()
        );

        lblReportDate.setText(
                "Report Date: "
                + java.time.LocalDate.now().toString()
        );

        if (treatments.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "No patient treatment records found."
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error generating patient treatment report: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnPatientTreatmentReportActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       DashboardJFrame dashboard = new DashboardJFrame();

    dashboard.setVisible(true);

    this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDailyReport;
    private javax.swing.JButton btnGenerateDaily;
    private javax.swing.JButton btnMonthlyReport;
    private javax.swing.JButton btnPatientTreatmentReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDailyReportTitle;
    private javax.swing.JLabel lblReportDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalAppointments;
    private javax.swing.JTable tblDailyAppointments;
    // End of variables declaration//GEN-END:variables
}
