/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.TreatmentController;
import model.Treatment;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TreatmentsJFrame extends javax.swing.JFrame {
    private TreatmentController treatmentController;

    /**
     * Creates new form TreatmentsJFrame
     */
   public TreatmentsJFrame() {
    initComponents();

    treatmentController = new TreatmentController();

    loadTreatments();

    jTable1.getSelectionModel().addListSelectionListener(e -> {

        if (!e.getValueIsAdjusting()) {

            int row = jTable1.getSelectedRow();

            if (row >= 0) {

                jTextField4.setText(
                    jTable1.getValueAt(row, 0).toString()
                );

                jTextField1.setText(
                    jTable1.getValueAt(row, 1).toString()
                );

                jTextField2.setText(
                    jTable1.getValueAt(row, 2).toString()
                );

                jTextField3.setText(
                    jTable1.getValueAt(row, 3).toString()
                );
            }
        }
    });
}
   private void loadTreatments() {

    try {

        List<Treatment> treatments =
                treatmentController.getAllTreatments();

        DefaultTableModel model =
                (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Treatment treatment : treatments) {

            model.addRow(new Object[]{
                treatment.getTreatmentId(),
                treatment.getTreatmentName(),
                treatment.getDescription(),
                treatment.getFee()
            });
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error loading treatments: "
                + e.getMessage()
        );
    }
}
   private void clearFields() {

    jTextField4.setText("");
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");

    jTable1.clearSelection();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TREATMENT MANAGEMENT");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("TREATMENT MANAGEMENT");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Treatment Name:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Description:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Fee:");

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Treatment ID:");

        jButton5.setBackground(new java.awt.Color(0, 0, 102));
        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Treatment ID", "Treatment Name", "Description", "Fee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("© 2026 Sunrise Dental Clinic ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sunrise_dental_clinic_logo_135x110.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(80, 80, 80)
                .addComponent(jButton3)
                .addGap(82, 82, 82)
                .addComponent(jButton5)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(37, 37, 37)
                .addComponent(jButton4)
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       DashboardJFrame dashboard = new DashboardJFrame();
dashboard.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {

        // ==============================
        // 1. REQUIRED FIELD VALIDATION
        // ==============================

        String name =
                jTextField1.getText().trim();

        String description =
                jTextField2.getText().trim();

        String feeText =
                jTextField3.getText().trim();


        if (name.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Treatment Name!"
            );

            jTextField1.requestFocus();
            return;
        }


        if (description.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Treatment Description!"
            );

            jTextField2.requestFocus();
            return;
        }


        if (feeText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Treatment Fee!"
            );

            jTextField3.requestFocus();
            return;
        }


        // ==============================
        // 2. TREATMENT NAME VALIDATION
        // ==============================

        if (!name.matches("[a-zA-Z0-9 .&()/-]+")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Treatment Name contains invalid characters!"
            );

            jTextField1.requestFocus();
            return;
        }


        // ==============================
        // 3. DESCRIPTION VALIDATION
        // ==============================

        if (description.length() < 3) {

            JOptionPane.showMessageDialog(
                    this,
                    "Description must contain at least 3 characters!"
            );

            jTextField2.requestFocus();
            return;
        }


        // ==============================
        // 4. FEE VALIDATION
        // ==============================

        double fee =
                Double.parseDouble(feeText);

        if (fee <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Treatment Fee must be greater than 0!"
            );

            jTextField3.requestFocus();
            return;
        }


        // ==============================
        // 5. CREATE TREATMENT
        // ==============================

        Treatment treatment =
                new Treatment();

        treatment.setTreatmentName(name);
        treatment.setDescription(description);
        treatment.setFee(fee);


        // ==============================
        // 6. SAVE TREATMENT
        // ==============================

        boolean saved =
                treatmentController.saveTreatment(treatment);


        if (saved) {

            JOptionPane.showMessageDialog(
                    this,
                    "Treatment Saved Successfully!"
            );

            loadTreatments();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Treatment already exists!"
            );
        }


    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Treatment Fee must be a valid number!"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Database Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try {

        // ==============================
        // 1. TREATMENT ID VALIDATION
        // ==============================

        String idText =
                jTextField4.getText().trim();

        if (idText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a treatment from the table first!"
            );

            return;
        }

        int treatmentId =
                Integer.parseInt(idText);

        if (treatmentId <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid Treatment ID!"
            );

            return;
        }


        // ==============================
        // 2. TREATMENT NAME VALIDATION
        // ==============================

        String name =
                jTextField1.getText().trim();

        if (name.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Treatment Name!"
            );

            jTextField1.requestFocus();
            return;
        }

        if (!name.matches("[a-zA-Z0-9 .&()/-]+")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Treatment Name contains invalid characters!"
            );

            jTextField1.requestFocus();
            return;
        }


        // ==============================
        // 3. DESCRIPTION VALIDATION
        // ==============================

        String description =
                jTextField2.getText().trim();

        if (description.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Treatment Description!"
            );

            jTextField2.requestFocus();
            return;
        }

        if (description.length() < 3) {

            JOptionPane.showMessageDialog(
                    this,
                    "Description must contain at least 3 characters!"
            );

            jTextField2.requestFocus();
            return;
        }


        // ==============================
        // 4. FEE VALIDATION
        // ==============================

        String feeText =
                jTextField3.getText().trim();

        if (feeText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Treatment Fee!"
            );

            jTextField3.requestFocus();
            return;
        }

        double fee =
                Double.parseDouble(feeText);

        if (fee <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Treatment Fee must be greater than 0!"
            );

            jTextField3.requestFocus();
            return;
        }


        // ==============================
        // 5. CREATE TREATMENT
        // ==============================

        Treatment treatment =
                new Treatment();

        treatment.setTreatmentId(treatmentId);
        treatment.setTreatmentName(name);
        treatment.setDescription(description);
        treatment.setFee(fee);


        // ==============================
        // 6. UPDATE TREATMENT
        // ==============================

        boolean updated =
                treatmentController.updateTreatment(treatment);

        if (updated) {

            JOptionPane.showMessageDialog(
                    this,
                    "Treatment Updated Successfully!"
            );

            // Refresh table
            loadTreatments();

            // Clear fields
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Treatment ID not found!"
            );
        }


    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Treatment ID and Fee must be valid numbers!"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Database Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {

        // ==============================
        // 1. TREATMENT ID VALIDATION
        // ==============================

        String idText =
                jTextField4.getText().trim();

        if (idText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a treatment first!"
            );

            return;
        }

        int treatmentId =
                Integer.parseInt(idText);

        if (treatmentId <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Invalid Treatment ID!"
            );

            return;
        }


        // ==============================
        // 2. CONFIRM DELETE
        // ==============================

        int confirm =
                JOptionPane.showConfirmDialog(
                        this,
                        "Are you sure you want to delete this treatment?",
                        "Confirm Delete",
                        JOptionPane.YES_NO_OPTION
                );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }


        // ==============================
        // 3. DELETE TREATMENT
        // ==============================

        boolean deleted =
                treatmentController.deleteTreatment(treatmentId);


        // ==============================
        // 4. RESULT
        // ==============================

        if (deleted) {

            JOptionPane.showMessageDialog(
                    this,
                    "Treatment Deleted Successfully!"
            );

            loadTreatments();
            clearFields();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Cannot delete this treatment.\n"
                    + "It is already used in an appointment."
            );
        }


    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Treatment ID must be a valid number!"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Database Error: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          clearFields();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreatmentsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreatmentsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreatmentsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreatmentsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreatmentsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
